title: Fabiano Calado
description: Data Science
baseurl: "" # the subpath of your site, e.g. /blog
url: "caladoxd.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2016_style/img/icon-large.png"

social: 
  name: Linkedin
  link: "https://www.linkedin.com/in/fabiano-calado-a84b5371/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: #['_2016_pages', '_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/fabiano-calado-a84b5371/

# Build settings
markdown: kramdown
permalink: pretty
